$schema: http://json-schema.org/draft-07/schema#
$id: https://schema.kyelang.org/schema.json
title: Compiled Kye schema
description: The schema for compiled Kye models
type: object
required: [ models ]
properties:
  models:
    description: The models in the schema
    type: object
    additionalProperties:
      $ref: "#/$defs/Model"
  types:
    description: The types in the schema
    type: object
    additionalProperties:
      $ref: "#/$defs/Type"
$defs:
  AbstractIndexes:
    description: The indexes of a model
    oneOf:
      - type: object
        required: [ indexes ]
        properties:
          indexes:
            type: array
            items:
              oneOf:
                - type: array
                  minItems: 1
                  items:
                    type: string
                - type: string
          index:
            not: {}
      - type: object
        required: [ index ]
        properties:
          index:
            oneOf:
              - type: array
                minItems: 1
                items:
                  type: string
              - type: string
          indexes:
            not: {}
  Model:
    description: A model in the schema
    type: object
    allOf:
      - $ref: "#/$defs/AbstractIndexes"
    required: [ edges ]
    additionalProperties: false
    properties:
      indexes: {}
      index: {}
      edges:
        description: The edges of the model
        type: object
        additionalProperties:
          $ref: "#/$defs/Edge"
      assertions:
        description: The assertions of the model
        type: array
        items:
          $ref: "#/$defs/Assertion"
      loc:
        description: The location of the model in the source code
        type: string
  Type:
    description: A type in the schema
    type: object
    additionalProperties: false
    properties:
      parent:
        description: The parent type
        type: string
      conditions:
        description: The conditions for the type
        type: array
        items:
          $ref: "#/$defs/Expr"
      edges:
        description: The edges of the type
        type: object
        additionalProperties:
          $ref: "#/$defs/Edge"
      assertions:
        description: The assertions of the type
        type: array
        items:
          $ref: "#/$defs/Assertion"
      loc:
        description: The location of the type in the source code
        type: string
  Edge:
    type: object
    required: [ type ]
    additionalProperties: false
    properties:
      type:
        description: The name of a type
        type: string
        examples: [ Number, String, Boolean ]
      title:
        description: The title of the edge
        type: string
      many:
        description: Whether the edge allows many values
        type: boolean
        default: false
      none:
        description: Whether the edge allows null values
        type: boolean
        default: false
      expr:
        description: The expression for a computed edge
        $ref: "#/$defs/Expr"
      loc:
        description: The location of the edge in the source code
        type: string
  Assertion:
    type: object
    required: [ msg, expr ]
    additionalProperties: false
    properties:
      msg:
        description: The message of the assertion
        type: string
      expr:
        description: The expression of the assertion
        $ref: "#/$defs/Expr"
      loc:
        description: The location of the assertion in the source code
        type: string
  Expr:
    type: array
    items:
      type: object
      # propertyNames:
      #   enum: [col, str, is_null, not_null, not, neg, ne, eq, or, and, len, lt, gt, lte, add, sub, mul, div, mod, concat, count]
      additionalProperties:
        oneOf:
          - type: 'null'
          - type: string
          - type: boolean
          - type: number
          - type: array
            items:
              oneOf:
                - type: string
                - type: boolean
                - type: number
      maxProperties: 1
      minProperties: 1